# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RTradeDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RTradeDemo
pod 'AFNetworking', '~> 3.1.0'
pod 'SDWebImage', '~> 4.0.0-beta2'
pod 'Masonry', '~> 1.0.2'
pod 'MJRefresh', '~> 3.1.12'
pod 'DateTools', '~> 1.7.0'

  target 'RTradeDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RTradeDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
